import AudioModel from "models/audio.model";
import AutoPlayListModel from "models/autogenerated-playlist";
import cron from "node-cron";

const generatePlaylists = async () => {
  try {
    const audios = await AudioModel.aggregate([
      { $sort: { likes: -1 } },
      { $sample: { size: 20 } },
      { $group: { _id: "$category", audios: { $push: "$$ROOT._id" } } },
    ]);

    audios.map(async (item) => {
      await AutoPlayListModel.updateOne({ title: item._id }, { $set: { items: item.audios } }, { upsert: true });
    });
  } catch (error) {
    console.log(error);
  }
};

cron.schedule("0 0 * * *", async () => {
  await generatePlaylists();
});
