import { Router } from "express";
import ProfileController from "../controllers/profile.controller";
import { isAuthenticatedMiddleware } from "../middlewares/is-authenticated.middleware";
import { isVerifiedMiddleware } from "../middlewares/is-verified.middleware";
import { shouldBeAuthenticatedMiddleware } from "../middlewares/shouldBeAuthenticatedMiddleware";

const router: any = Router();

router.post("/follow/:profileId", isAuthenticatedMiddleware, isVerifiedMiddleware, ProfileController.followProfile);

router.post("/unfollow/:profileId", isAuthenticatedMiddleware, isVerifiedMiddleware, ProfileController.unfollowProfile);

router.get("/audios-total-count", isAuthenticatedMiddleware, isVerifiedMiddleware, ProfileController.getAudiosTotalCount);

router.get("/audios", isAuthenticatedMiddleware, isVerifiedMiddleware, ProfileController.getAudios);

router.get("/recommended", shouldBeAuthenticatedMiddleware, ProfileController.getRecommendedAudios);

router.get("/auto-generated-playlists", isAuthenticatedMiddleware, isVerifiedMiddleware, ProfileController.getAutoGeneratedPlaylists);

router.get("/followers", isAuthenticatedMiddleware, ProfileController.getFollowers);

router.get("/followers/:profileId", isAuthenticatedMiddleware, ProfileController.getFollowersForPublicProfile);

router.get("/followings", isAuthenticatedMiddleware, ProfileController.getFollowings);

router.get("/:profileId", ProfileController.getPublicProfile);

router.get("/playlists/:profileId", ProfileController.getPublicPlaylists);

router.get("/playlist-audios/:playlistId", ProfileController.getPlaylistAudios);

router.get("/private-playlist-audios/:playlistId", isAuthenticatedMiddleware, ProfileController.getPrivatePlaylistAudios);

router.get("/is-following/:profileId", isAuthenticatedMiddleware, ProfileController.getIsFollowing);

export default router;
